extends Node

@warning_ignore("unused_signal")
signal unit_moved(unit)
@warning_ignore("unused_signal")
signal turn_changed(team)
@warning_ignore("unused_signal")
signal request_highlight(cells)
@warning_ignore("unused_signal")
signal request_clear_highlight()
@warning_ignore("unused_signal")
signal request_move_unit(unit, cell)
@warning_ignore("unused_signal")
signal request_move_along_path(unit, path)
@warning_ignore("unused_signal")
signal request_ai_move_along_path(unit, path)
@warning_ignore("unused_signal")
signal request_show_menu(unit)
@warning_ignore("unused_signal")
signal request_hide_menu()
@warning_ignore("unused_signal")
signal request_show_victory(winning_team)
@warning_ignore("unused_signal")
signal request_highlight_unit(unit)
@warning_ignore("unused_signal")
signal request_clear_highlight_unit()
@warning_ignore("unused_signal")
signal request_screen_shake(duration: float, intensity: float, direction: Vector2)
@warning_ignore("unused_signal")
signal request_damage_popup(world_pos: Vector2, damage: int, is_crit: bool, is_miss: bool, is_heal: bool)
@warning_ignore("unused_signal")
signal request_show_info(unit)
@warning_ignore("unused_signal")
signal request_hide_info()
@warning_ignore("unused_signal")
signal request_show_setting()
@warning_ignore("unused_signal")
signal request_hide_setting()
@warning_ignore("unused_signal")
signal speed_changed(new_speed: int)
@warning_ignore("unused_signal")
signal request_show_enemy_preview(move_cells, attack_cells, attack_color)
@warning_ignore("unused_signal")
signal request_dialogue_check(unit)
@warning_ignore("unused_signal")
signal battle_completed(winning_team: int)
@warning_ignore("unused_signal")
signal non_combat_complete()
